### ISSUE TITLE
Sliding Cart

### ISSUE THREAD

**Issue by daAnzeigeBaws** [Pzzio/EPOS#27]
The sliding Cart on development is not working due to a JS error in notVueInstructions (refer to the console output if you try it).
Please fix it!

**Comment by MrMinimal** [comment]
The shopping cart div in Tobi's index.html was lost in a merge.
Readded it in 363b70d5a46faebaec90defeeaec76271bdd0874 and 784d8a4677f2bca383376e928b0d9e06ef6319d3
