### ISSUE TITLE
Petri Netz prüfen und Abgleich mit Software implementierung

### ISSUE THREAD

**Issue by highperformancedevelopments** [Pzzio/EPOS#39]
vgl. Aufgabenstellung 4 der Aufgabe. --> wird von mir erledigt.
Weiterhin prüfen ob Petri-Netz mit unserer Implementierung aus Prozesssicht übereinstimmt. --> Hilfe erwünscht.

**Comment by MrMinimal** [comment]
Damit du das Netz mit der Implementierung abgleichen kannst, solltest du die Website schon sehen koennen. Kann @keinproblem nochmal auf Heroku updaten?

**Comment by highperformancedevelopments** [comment]
@MrMinimal @keinproblem 
Wie schauts bzgl. des Hostings der aktuellen Version ?

Dann würde ich mich gleich dem ganzen widmen, das Wochenende und die Abgabe naht.

**Comment by highperformancedevelopments** [comment]
Website lokal bei mir am laufen. Hosting hat sich erledigt. Dokument mit dem Abgleich folgt.

**Comment by highperformancedevelopments** [comment]
Dokument mit dem Abgleich liegt ebenfalls im Branch Petri-Netz. Petri-Netz ist fertig, den Abgleich werde ich bei Bedarf nochmal überarbeiten wenn mir weitere Infos vorliegen sollten.

**Comment by highperformancedevelopments** [comment]
Dokument mit dem Abgleich liegt ebenfalls im Branch Petri-Netz. Petri-Netz ist fertig, den Abgleich werde ich bei Bedarf nochmal überarbeiten wenn mir weitere Infos vorliegen sollten.
