### ISSUE TITLE
Button "remove all" in Cart without function 

### ISSUE THREAD

**Issue by highperformancedevelopments** [Pzzio/EPOS#41]
Button gets displayed but don't work.
Issue in context with single remove button ?

**Comment by keinproblem** [comment]
Please ensure that you have the most recent version in use

**Comment by highperformancedevelopments** [comment]
Used recent development branch cloned this morning.

**Comment by highperformancedevelopments** [comment]
The updated development branch fixes the bug. Issue could be closed.
Remove all and selective remove (incl. the first row of the cart) work properly.
