### ISSUE TITLE
Special ingredients not selectable

### ISSUE THREAD

**Issue by highperformancedevelopments** [Pzzio/EPOS#42]
At Pizza Romana special ingredients onion and olives are not selectable.
Issue is that the site footer is overlaying the list elements --> footer set with debugger to height 0 list elements are selectable without problems.

**Comment by highperformancedevelopments** [comment]
Concerns all pizzas with more than 3 special ingredients.

**Comment by daAnzeigeBaws** [comment]
This is a design related problem. The footer is not to blame for this, it is about the extra ingredients not rendering in an optimal way

**Comment by highperformancedevelopments** [comment]
Bug fixed by @daAnzeigeBaws .
Selection now works properly.
