### ISSUE TITLE
Create test cases

### ISSUE THREAD

**Issue by daAnzeigeBaws** [Pzzio/EPOS#6]
Every business process gets its own test case

**Comment by keinproblem** [comment]
I'd suggest to create several test-scenarios for the respective business processes.
In this testing model we'd have the following abstraction layers of operations (decreasing abstraction level):
- Black-Box Tests
    - Use Case Operations
    - Validation Testing
- White-Box Tests
    - Integration Testing
    - Unit Testing

Obviously, Tests consist of valid and invalid operations to ensure the proper behavior of components, especially for error handling.
